name: whishapp
description: Enhancing your WhatsApp experience.
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_pickers: ^2.0.0
  flutter_hooks: ^0.18.1
  url_launcher: ^6.0.12
  path: ^1.8.0
  path_provider: ^2.0.6
  bot_toast: ^4.0.1
  mime: ^1.0.1
  open_file: ^3.2.1
  permission_handler: ^10.1.0
  share_plus: ^4.5.3
  photo_view: ^0.14.0
  intl: ^0.17.0
  flutter_svg: ^1.1.5
  video_thumbnail: ^0.5.3
  better_player: ^0.0.79
  whatsapp_unilink: ^2.0.0
  flutter_whatsapp_stickers: ^1.0.1+5
  package_info_plus: ^1.3.0
  cross_file: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
